---
title: "Projet ADM Q5"
author: "RODRIGUES Camille-Astrid AMOUROUX Jan"
date: "`r Sys.Date()`"
output: 
  htlm_document:
    code_folding: hide
    toc: TRUE
    cache: TRUE
editor_options: 
  chunk_output_type: console
---

```{r include=FALSE}
knitr::opts_chunk$set(fig.align="center", fig.width=6, fig.height=6, fig.path="Figs/", echo=TRUE, warning=FALSE, message=FALSE, cache=TRUE)
```

```{r, include= F}
library(tidyverse)
library(ade4)

#library(rpart)

#library(MASS)
```

======================= QUESTION 4 =======================

--\> habitat : urbanisation

--\> espèces : taille

Ouverture des données

```{r}
habitat = read.table("../data/habitat.tsv", sep = "\t",
                     stringsAsFactors = T, header = T, na.strings = T)
especes = read.table("../data/especes.tsv", sep = "\t",
                     stringsAsFactors = T, header = T, na.strings = T)
```

==\> impact de l'urbanisation sur la taille des oiseaux (diminution de la taille pour se cacher de l'Homme ?)

ANALYSE :

-   ==\> chi² entre espece\$taille et habitat\$bati

Problème, on a des problèmes de dimentions, nécécité de faire des subsets : 




-   ==\> modèle linéaire

==\> conclure :
